name: Buildozer Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Use supported python version

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          openjdk-11-jdk \
          python3-pip \
          build-essential \
          git \
          zip \
          unzip \
          libncurses5 \
          libffi-dev \
          libssl-dev \
          autoconf \
          automake \
          libtool \
          pkg-config \
          zlib1g-dev \
          curl

    - name: Install Buildozer and Cython
      run: |
        python3 -m pip install --upgrade pip
        pip install --upgrade buildozer cython

    - name: Download Android SDK Command line tools
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        cd $ANDROID_SDK_ROOT/cmdline-tools
        curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools.zip
        rm commandlinetools.zip
        mv cmdline-tools latest

    - name: Setup environment variables
      run: |
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH

    - name: Install Android SDK packages
      run: |
        yes | sdkmanager --sdk_root=${ANDROID_SDK_ROOT} --licenses
        sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    - name: Build APK with Buildozer
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: bin/*.apk
