name: Kivy Android Build

on:
  push:
    branches:
      - main  # या आपकी डिफ़ॉल्ट ब्रांच का नाम

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Kivy और Buildozer के लिए उपयुक्त Python संस्करण चुनें

    - name: Install Buildozer and dependencies
      run: |
        pip install buildozer
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libssl-dev libffi-dev libsqlite3-dev libxml2-dev libxslt1-dev libjpeg-dev libpng-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

    - name: Initialize Buildozer (if buildozer.spec doesn't exist)
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Update buildozer.spec (Optional, adjust as needed)
      run: |
        # यहाँ आप buildozer.spec फ़ाइल में बदलाव कर सकते हैं, जैसे ऐप का नाम, पैकेज का नाम, आदि।
        # उदाहरण के लिए:
        sed -i 's/^title = My Application/title = MyKivyApp/' buildozer.spec
        sed -i 's/^package.name = myapp/package.name = mykivyapp/' buildozer.spec
        sed -i 's/^requirements = python3,kivy/requirements = python3,kivy,pillow/' buildozer.spec # अपनी आवश्यकताओं के अनुसार जोड़ें
        sed -i 's/^android.api = 27/android.api = 33/' buildozer.spec # नवीनतम Android API स्तर
        sed -i 's/^android.minapi = 21/android.minapi = 21/' buildozer.spec
        sed -i 's/^android.archs = armeabi-v7a,arm64-v8a/android.archs = arm64-v8a/' buildozer.spec # केवल arm64-v8a के लिए

    - name: Build Android APK
      run: |
        buildozer android debug # या 'buildozer android release' यदि आप रिलीज़ बिल्ड चाहते हैं

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: kivy-apk
        path: bin/*.apk # Buildozer द्वारा उत्पन्न APK फ़ाइलें
