name: Build Android APK

on: push: branches: - main

jobs: build: runs-on: ubuntu-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Set up Python 3.10
    uses: actions/setup-python@v5
    with:
      python-version: '3.10'

  - name: Install system dependencies
    run: |
      sudo apt update
      sudo apt install -y zip unzip openjdk-17-jdk wget

  - name: Install buildozer and dependencies
    run: |
      python -m pip install --upgrade pip
      pip install cython==0.29.36
      pip install buildozer

  - name: Create Android SDK license file
    run: |
      mkdir -p ~/.android
      echo '24333f8a63b6825ea9c5514f83c2829b004d1fee' > ~/.android/repositories.cfg

  - name: Initialize buildozer
    run: buildozer init || true

  - name: Build APK
    run: buildozer android debug

  - name: Upload APK
    uses: actions/upload-artifact@v3
    with:
      name: app-release.apk
      path: bin/*.apk

