name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libffi-dev libssl-dev \
              libncurses5-dev libsqlite3-dev libreadline-dev libgdbm-dev \
              libbz2-dev zlib1g-dev liblzma-dev build-essential \
              libxml2-dev libxslt-dev libjpeg-dev libfreetype6-dev \
              libavcodec-dev libavformat-dev libswscale-dev \
              openjdk-8-jdk unzip

          pip install --upgrade pip
          pip install buildozer cython

      - name: Download Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

      - name: Set environment
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          echo "$HOME/android-sdk/emulator" >> $GITHUB_PATH
          echo "$HOME/android-sdk/tools/bin" >> $GITHUB_PATH

      - name: Accept Licenses
        run: yes | sdkmanager --licenses

      - name: Install Android SDK components
        run: |
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-release
          path: bin/*.apk
