name: build-android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y unzip zip openjdk-17-jdk python3-pip python3-setuptools

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install cython==0.29.36
          pip install buildozer

      - name: Accept Android SDK licenses
        run: |
          mkdir -p ~/.android
          echo '### User Agreements' > ~/.android/repositories.cfg
          yes | buildozer android clean
        shell: bash

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: android-apk
          path: bin/*.apk
