on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3    # latest stable checkout action

      - name: Build APK
        uses: digreatbrian/buildozer-action@v1   # ye abhi tak latest stable lagta hai
        with:
          buildozer-cmd: buildozer -v android debug
          work-dir: .  # jahan tumhara main.py hai

      - name: Upload artifacts
        uses: actions/upload-artifact@v3    # latest stable upload artifact action
        with:
          name: package
          path: ./bin/*.apk
