name: build-android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer Cython

      - name: Set up Android SDK license
        run: |
          mkdir -p ~/.android
          echo "### Accepting licenses" 
          echo -e "\n### Google SDK license agreement" 
          echo '24333f8a63b6825ea9c5514f83c2829b004d1fee' > ~/.android/repositories.cfg || true

      - name: Initialize Buildozer
        run: buildozer init || true

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-debug.apk
          path: bin/*.apk
